name: Tele Bot Alert

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows manual trigger from GitHub UI

jobs:
  check-and-post:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm install axios dotenv

      - name: Run Telegram Bot Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOPIC_ID: ${{ secrets.TELEGRAM_TOPIC_ID }}
        run: |
          curl -L -o telebotpost.js ${{ secrets.TELEBOTPOST_SCRIPT }}
          node telebotpost.js
      
      - name: Changes ko commit karen
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/abidprobook/TelebotPost.git

      - name: Commit and push changes
        run: |
          git add posted_channels_state.json embeded.json skysun.json schedule.json
          git fetch origin main
          git reset --soft origin/main
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Fetch TELEBOTPOST latest data"
            git push origin main
          fi
